name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps
    - name: Generate shortcut
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=truelayer_coding_challenge\">" > target/doc/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/doc # The folder the action should deploy.
    
